tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "on-tertiary-container": "#a77b4e",
        "surface": "#e5feff",
        "error": "#ba1a1a",
        "tertiary": "#000000",
        "inverse-surface": "#1c3435",
        "surface-bright": "#e5feff",
        "surface-container": "#d8f3f4",
        "on-surface": "#051f20",
        "primary-fixed-dim": "#c7c6ca",
        "primary-fixed": "#e3e2e6",
        "surface-container-high": "#d2edee",
        "on-background": "#051f20",
        "secondary-container": "#e5e2dc",
        "on-error": "#ffffff",
        "on-tertiary": "#ffffff",
        "tertiary-fixed": "#ffdcbd",
        "error-container": "#ffdad6",
        "surface-dim": "#c4dfe0",
        "surface-container-highest": "#cde8e9",
        "background": "#e5feff",
        "primary-container": "#1a1b1e",
        "on-tertiary-fixed": "#2c1600",
        "on-secondary-container": "#656460",
        "inverse-primary": "#c7c6ca",
        "surface-variant": "#cde8e9",
        "on-tertiary-fixed-variant": "#623f18",
        "on-primary": "#ffffff",
        "on-error-container": "#93000a",
        "outline": "#76777b",
        "inverse-on-surface": "#dbf6f7",
        "tertiary-container": "#2c1600",
        "on-secondary-fixed-variant": "#474743",
        "tertiary-fixed-dim": "#f0bd8b",
        "on-primary-fixed": "#1a1b1e",
        "on-secondary": "#ffffff",
        "primary": "#000000",
        "on-surface-variant": "#46474a",
        "outline-variant": "#c7c6cb",
        "secondary-fixed": "#e5e2dc",
        "on-secondary-fixed": "#1c1c18",
        "on-primary-fixed-variant": "#46474a",
        "surface-tint": "#5e5e62",
        "surface-container-lowest": "#ffffff",
        "secondary": "#5f5e5a",
        "secondary-fixed-dim": "#c9c6c1",
        "on-primary-container": "#848387",
        "surface-container-low": "#def9fa"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      "spacing": {
        "margin-mobile": "20px",
        "gutter": "24px",
        "unit": "4px",
        "grid-cols": "12",
        "margin-desktop": "64px"
      },
      "fontFamily": {
        "display-hero-mobile": ["Syne"],
        "headline-lg": ["Syne"],
        "label-technical": ["Space Mono"],
        "headline-lg-mobile": ["Syne"],
        "display-hero": ["Syne"],
        "body-md": ["Hanken Grotesk"]
      },
      "fontSize": {
        "display-hero-mobile": ["48px", {"lineHeight": "44px", "letterSpacing": "-0.02em", "fontWeight": "800"}],
        "headline-lg": ["64px", {"lineHeight": "64px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "label-technical": ["12px", {"lineHeight": "16px", "fontWeight": "400"}],
        "headline-lg-mobile": ["32px", {"lineHeight": "36px", "fontWeight": "700"}],
        "display-hero": ["120px", {"lineHeight": "100px", "letterSpacing": "-0.04em", "fontWeight": "800"}],
        "body-md": ["18px", {"lineHeight": "28px", "fontWeight": "400"}]
      }
    },
  },
}